#+STARTUP: content logdone hideblocks
#+TODO: TASK(t!) | DONE(d) CANCEL(c)
#+TODO: BUG(b!) | FIXED(f) REJECT(r)
#+PRIORITIES: A F C
#+TAGS: current(c) testing(t)
#+CONSTANTS: last_issue_id=4

* Задачи
  :PROPERTIES:
  :COLUMNS:  %3issue_id(ID) %4issue_type(TYPE) %TODO %40ITEM %SCHEDULED %DEADLINE %1PRIORITY
  :ARCHIVE:  tasks_archive.org::* Архив задач
  :END:

** TASK Добавить информацию о скриншоте с ошибкой 404
   :PROPERTIES:
   :issue_id: 1
   :issue_type: task
   :END:

   [2022-03-05 Сб]

   При закачивании скриншота на его месте может быть какая-то
   HTTP-ошибка. Нужно сделать обработчик ошибки 404. Также бывает ещё
   перезакачивание, в котором тоже нужно обрабатывать аналогичный
   результат загрузки. Если скриншот не закачался правильно, нужно
   сообщить об этом в лог-файле.

** TASK Добавить ещё один сайт со скриншотами
   :PROPERTIES:
   :issue_id: 2
   :issue_type: task
   :END:

   [2022-03-06 Вс]

   Бывают топики, в которых изображения хранятся не на fastpic.org и
   при этом изображения отображаются в браузере (их можно
   скачать). Нужно обрабатывать такие изображения тоже.

** TASK Подготовить код для создания цепочки конвертаций
   :PROPERTIES:
   :issue_id: 4
   :issue_type: task
   :END:

   [2022-03-06 Вс]

   Для гибкости программы нужно добавить выбор стратегии разбора
   страницы, преобразования промежуточных данных, построения конечных
   команд закачки. Разные виды топиков могут потребовать сильно
   различающихся действий над ними с индивидуальными
   процедурами. Такие сильно различающиеся цепочки разбора,
   конвертации и построения могут обнаруживаться как в пределах одного
   вида топика, так и в пределах нескольких разных видов топиков.


* Баги
  :PROPERTIES:
  :COLUMNS:  %3issue_id(ID) %4issue_type(TYPE) %TODO %40ITEM %SCHEDULED %DEADLINE %1PRIORITY
  :ARCHIVE:  tasks_archive.org::* Архив багов
  :END:


* Окружение проекта
  :PROPERTIES:
  :COLUMNS:  %3issue_id(ID) %4issue_type(TYPE) %TODO %40ITEM %SCHEDULED %DEADLINE %1PRIORITY
  :ARCHIVE:  tasks_archive.org::* Архив окружения
  :END:

** TASK Добавить комментарии ко всем функциям в скрипте
   :PROPERTIES:
   :issue_id: 3
   :issue_type: task
   :END:

   [2022-03-06 Вс]

   [2022-03-18 Пт]

   Добавил комментарии поверхностные. Надо добавить в комментарии
   информацию про поля для awk, иначе непонятно, что принимает функция
   в качестве аргументов.

   Дальше нужно добавить более полные комментарии в виде:
   #+BEGIN_EXAMPLE
     Строка короткое описание;
     Строка детальное описание1
     Строка детальное описание2
     ...
     Строка детальное описаниеN;
     Строка с принимаемыми аргументами и возвращаемым значением;
   #+END_EXAMPLE

   Возможно, надо будет придумать синтаксис, который точно покажет,
   как функция принимает аргументы и как функция возвращает
   значение. Функция может принимать stdin и/или аргументы и может
   возвращать stdout и/или return value.
