.\"
.\" This manpage is a part of __PROGRAM_NAME__ __PROGRAM_VERSION__
.\"
.\" __PROGRAM_COPYRIGHT__ __PROGRAM_AUTHOR__ __PROGRAM_AUTHOR_EMAIL__
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"

.TH __PROGRAM_NAME__ "5" "__PROGRAM_DATE__" "__PROGRAM_NAME__ __PROGRAM_VERSION__" "File Formats"

.SH NAME

__FNAME_ETC_CONFIG__ \- __PROGRAM_NAME__ configuration for all users

.SH DESCRIPTION

The configuration file has format as several lines separated by
newlines with a pair on every line in the format

.PP
  key=value

The program at first uses the general file from
.I __DNAME_ETC_CONFIG__/__FNAME_ETC_CONFIG__
to set its configuration and then uses the second file
.I __DNAME_HOME_CONFIG__/__FNAME_HOME_CONFIG__
edited by the user to override key-value pairs.

.PP
These keys are available:

.TP
.B topic_proxy
Set a proxy for the topic page downloading.
.br
Values are
.B on
or
.B off
.br
By default it is off.

.TP
.B topic_proxy_host
Set the proxy host for the topic page downloading.
.br
Value is a domain name or an ip-address.
.br
By default it is empty.

.TP
.B topic_proxy_port
Set the proxy port for the topic page downloading.
.br
Value is a decimal number.
.br
By default it is empty.

.TP
.B topic_proxy_type
Set the proxy type for the topic page downloading.
.br
Values are
.B socks4
or
.B socks5
.br
By default it is empty.

.TP
.B topic_proxy_user
Set the proxy user for the topic page downloading.
.br
The type of proxy should be socks5.
.br
Value is a string.
.br
By default it is empty.

.TP
.B topic_proxy_password
Set the proxy password for the topic page downloading.
.br
The type of proxy should be socks5.
.br
Value is a string.
.br
By default it is empty.

.TP
.B image_proxy
Set a proxy for the image file downloading.
.br
Values are
.B on
or
.B off
.br
By default it is off.

.TP
.B image_proxy_host
Set the proxy host for the image file downloading.
.br
Value is a domain name or an ip-address.
.br
By default it is empty.

.TP
.B image_proxy_port
Set the proxy port for the image file downloading.
.br
Value is a decimal number.
.br
By default it is empty.

.TP
.B image_proxy_type
Set the proxy type for the image file downloading.
.br
Values are
.B socks4
or
.B socks5
.br
By default it is empty.

.TP
.B image_proxy_user
Set the proxy user for the image file downloading.
.br
The type of proxy should be socks5.
.br
Value is a string.
.br
By default it is empty.

.TP
.B image_proxy_password
Set the proxy password for the image file downloading.
.br
The type of proxy should be socks5.
.br
Value is a string.
.br
By default it is empty.

.SH EXAMPLE

.PP
In this example we set configuration as different proxies for the topic page
and for the each image file.

.nf
    topic_proxy=on
    topic_proxy_host=somehost
    topic_proxy_port=1080
    topic_proxy_type=socks4
    topic_proxy_user=
    topic_proxy_password=

    image_proxy=on
    image_proxy_host=123.456.789.001
    image_proxy_port=8080
    image_proxy_type=socks5
    image_proxy_user=john
    image_proxy_password=smith
.fi

.PP
After that the program will download topic pages through a sock4 proxy.
.br
And each file will be downloaded through a socks5 proxy with a user and a password.

.PP
You can set off any proxy or both of them.

.SH AUTHOR

Written by __PROGRAM_AUTHOR__

.SH "REPORTING BUGS"

Go to the project site __PROGRAM_SITE__ and make a topic about bug or send a message to E-mail __PROGRAM_AUTHOR_EMAIL__.

.SH COPYRIGHT

__PROGRAM_COPYRIGHT__ __PROGRAM_AUTHOR__ __PROGRAM_AUTHOR_EMAIL__
.br
__PROGRAM_LICENSE__

.SH FILES

.TP
\fI __DNAME_ETC_CONFIG__/__FNAME_ETC_CONFIG__ \fR
configuration for all users

.TP
\fI __DNAME_HOME_CONFIG__/__FNAME_HOME_CONFIG__ \fR
configuration for the current user

.SH "SEE ALSO"

.BR __PROGRAM_NAME__ (1)
